### PR TITLE
314 Setup eslint extending airbnb and prettierjs

### PR DESCRIPTION
**Pull request by midhunkrishna**
from https://github.com/Terrastories/terrastories/issues/314 

- [x] Setup ESLint
- [x] Configure ESLint
- [x] Add documentation for developers to integrate with text editor

@kalimar Can you point me to a documentation page to which the developer integration notes to be added? Perhaps another section here -> https://github.com/Terrastories/terrastories/blob/master/SETUP.md

### CODE REVIEW

**Comment by midhunkrishna** [comment]
@mirandawang @MxOliver @kalimar Can you point me to a documentation page to which the developer integration notes to be added? Perhaps another section here -> https://github.com/Terrastories/terrastories/blob/master/SETUP.md

**Comment by kalimar** [comment]
@midhunkrishna that's the right place for a new section. Perhaps `Setting up your Development Environment`?

**Comment by midhunkrishna** [comment]
@kalimar Documentation added. 

Review pls @MxOliver @mirandawang

**Comment by mirandawang** [comment]
I'm wary to merge this in before we have any linting tests. I wouldn't want a bunch of unlinted code in our repo to fall upon one person to fix once we add the tests. How do you feel about adding some linting tests here? I can always open a separate issue for this work too, btw! @midhunkrishna 

Thanks for the contribution, this is great!! (: It will definitely help with the maintainability of quality in this code.

**Comment by midhunkrishna** [comment]
@mirandawang Can you elaborate on what you meant by linting tests?

**Comment by midhunkrishna** [comment]
@mirandawang ping

**Comment by midhunkrishna** [comment]
@mirandawang ping cc: @MxOliver @kalimar

**Comment by MxOliver** [comment]
So I'm not entirely sure if this is what @mirandawang meant, but linting tests would be tests written to ensure that code passes whatever linting configuration we are choosing. I found this which might be helpful https://api.rubyonrails.org/classes/ActiveModel/Lint/Tests.html

**Comment by MxOliver** [comment]
https://github.com/Terrastories/terrastories/issues/371

**Comment by midhunkrishna** [comment]
@MxOliver I still am confused about what the expectation is. In this PR, I have linter configured with airbnb defaults, with a lint script in package.json which runs on every precommit, that way, commits will fail when the code that is written is not properly linted. 

PR also has documentation for integrating eslint with code editors. 

Before any work from #371 is merged, please check: 

a) [Eslint Config](https://github.com/Terrastories/terrastories/pull/338/files#diff-df39304d828831c44a2b9f38cd45289cR7)
b) [package.json modifications](https://github.com/Terrastories/terrastories/pull/338/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R4)
c) [Pre Commit Hook](https://github.com/Terrastories/terrastories/pull/338/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11)

**Comment by midhunkrishna** [comment]
@MxOliver @mirandawang ping

**Comment by mirandawang** [comment]
@midhunkrishna Sorry for the late reply! Life + work got a little crazy.
And sorry for the confusion. Meant to ask about the linting script when I said tests.

Thanks for the helpful links! It looks like you already added everything we need. So we should be all good to merge :)

**Pull request merged**
