### PR TITLE
WIP: 268 display import errors

### PR DESCRIPTION
**Pull request by namel3ss**
This pull request introduces the following:

- The Import concern allows any controller to have import action that invokes the import method of its model. Additionally we have a similar concern in the routes as well.
- The Importable concern allows any model to support import by providing the importer class to be used. It expects the importer instance to be initialized with some data and respond to import.
- The base importer class is a template class for CSV importing. To create an importer for specific model, inherit from the base importer and define the import_row method for that specific model.
- Importers for the Place, Speaker and Story models. Implements the Importable and Import concerns in the models and their respective controllers. Clears out the importing code from the models and adds some DRY to the importing.
- Specs for the importable concern and the importers. Includes Stories, Speakers and Places importers.
- Marks `interview_location` and `interviewer` relations of the Story class as optional as per Rails 5+
- Minor UI fixes and visualisation of importing errors in the Admin area.

### CODE REVIEW

**Comment by namel3ss** [comment]
WIP, because I want to rebase on #295 once approved and merged.

**Comment by midhunkrishna** [comment]
@namel3ss #287 is merged !! :)

**Comment by namel3ss** [comment]
@midhunkrishna yes, already rebased and adjusting my stuff. Will ping you for feedback when ready :)

**Comment by mirandawang** [comment]
Hey there @namel3ss ! Is this still a WIP?

**Comment by FeminismIsAwesome** [comment]
Hey there @namel3ss hi is this still being worked on? we just did a refactor that will require rebasing (moving the Rails app to a Rails directory)

**Comment by FeminismIsAwesome** [comment]
@namel3ss sorry for not seeing this had a question until now! Yes, I think we still do need the ability to display import errors, so would love to be able to see this running in the new master.

Cheers,
Ian

**Comment by rudokemper** [comment]
Archiving this work, but closing the PR for now.

**Pull request closed without merging**
