### PR TITLE
WIP: [#285] Add place specs

### PR DESCRIPTION
**Pull request by sleekybadger**

### CODE REVIEW

**Comment by namel3ss** [comment]
@sleekybadger, FYI: in PR #300 I am removing the `import_csv` method from the model into an importer class.

**Comment by mirandawang** [comment]
@sleekybadger Hey there! Is this still being worked on?

**Comment by FeminismIsAwesome** [comment]
@sleekybadger hi is this still being worked on? we just did a refactor that will require rebasing (moving the Rails app to a Rails directory)

**Comment by FeminismIsAwesome** [comment]
closing for now, can be reopened when fixes applied.

**Pull request closed without merging**
