### PR TITLE
Add images for speakers avatars on seeds file

### PR DESCRIPTION
**Pull request by henriquepjv**
[Issue_353](https://github.com/Terrastories/terrastories/issues/353)

### Why
We had no images attached for Speakers images :disappointed: 

### How
Add new images in assets path and change the seeds file to populate the Speakers with the new images. :smiley:

### CODE REVIEW

**Comment by rudokemper** [comment]
Thanks for your work, @henriquepjv! Would you also be able to add some fake Place images for each place in the seed data?

**Comment by henriquepjv** [comment]
> Thanks for your work, @henriquepjv! Would you also be able to add some fake Place images for each place in the seed data?

Of course @rudokemper :+1: 
Already add the images for the places

**Comment by mirandawang** [comment]
Hey @henriquepjv, thanks for making this PR and thanks for your patience! We really appreciate it! :) 

I checked out your branch, but unfortunately I am not able to see the images from the seed data.

Here's an example of the image from seed data vs an image that I uploaded in the admin dashboard.
Screen Shot 2019-11-14 at 8 15 04 PM

And this is the Rails error that I'm getting:
```Parameters: {"content_type"=>"image/png", "disposition"=>"inline; filename=\"cat_with_glasses\"; filename*=UTF-8''cat_with_glasses", "encoded_key"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWRZbXRxY25FMlJ6WktVMHA0T1hkdmVsUTNURnBHWjBOaUJqb0dSVlE2RUdScGMzQnZjMmwwYVc5dVNTSkxhVzVzYVc1bE95Qm1hV3hsYm1GdFpUMGlZMkYwWDNkcGRHaGZaMnhoYzNObGN5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25ZMkYwWDNkcGRHaGZaMnhoYzNObGN3WTdCbFE2RVdOdmJuUmxiblJmZEhsd1pVa2lEbWx0WVdkbEwzQnVad1k3QmxRPSIsImV4cCI6IjIwMTktMTEtMTVUMDE6MTU6MzIuOTMxWiIsInB1ciI6ImJsb2Jfa2V5In19--5c0d8451fe49012107376918511d93b2022f5698", "filename"=>"cat_with_glasses"}
web_1  | Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)
web_1  |
web_1  |
web_1  |
web_1  | Errno::ENOENT - No such file or directory @ rb_file_s_mtime - /media/bk/jr/bkjrq6G6JSJx9wozT7LZFgCb:```

Could you take a look as to why the images aren't being attached the same way as when we do it thru the admin dashboard?

Thank you!!

**Comment by mirandawang** [comment]
Hey there @henriquepjv , are you still able to work on this?

**Comment by mirandawang** [comment]
Closing from inactivity

**Pull request merged**
