### PR TITLE
803 Allow super admin to view a "last updated on ..." note next to communities on the main dashboard

### PR DESCRIPTION
**Pull request by ashwini-seshadri**
This PR resolves issue #803 which allows super admin to view a "last updated on ..." note next to communities on the main dashboard.

- Added `Last updated on $date` on a new line following the name of the communities on the dashboard of super admin view page.
- Added the `last_updated_on` string to i18n `en` page for translation.

### CODE REVIEW

**Comment by ashwini-seshadri** [comment]
Hello @rudokemper 
The css (italics) part of the feature seem to not work. The file is not picking up or recognising the css element on the browser.
Can you please help/guide me in resolving that issue.
Also, can I use google translations to update other language's `last updated on`?

Screenshot 2022-10-24 at 11 50 57 PM

**Comment by rudokemper** [comment]
Hi @ashwini-seshadri, I think this needs a bit more work. When you create a community and navigate to the /communities view, it throws an error:

```
NoMethodError at /en/member/communities
undefined method `updated_at' for nil:NilClass

Hint: Something is `nil` when it probably shouldn't be.
```

Maybe we should set "Last updated on..." to be the $date when the community was created, if no updates have been found.

`Also, can I use google translations to update other language's last_updated_on?`

Yes I think it's fine to use google translate for the other languages.

`The css (italics) part of the feature seem to not work. The file is not picking up or recognising the css element on the browser.`

I see why this is happening. You are adding the CSS to the `admin` stylesheets which is for the old Administrate views, which are in the process of being refactored out. The CSS code should be added to one of the stylesheets in `cms` - maybe `_flex_table.scss` since that is what the rest of the table is drawing from.

**Comment by rudokemper** [comment]
That's great @ashwini-seshadri !

For Matawai, please feel free to use the Dutch translation; Dutch can be a fallback for Matawai (a native language spoken in Suriname, where Dutch is the colonial language.)

**Comment by ashwini-seshadri** [comment]
Hi @rudokemper 
I am unable to run tests using `docker-compose exec web rspec`
This is the error I get
Screenshot 2022-10-25 at 11 34 08 PM


The code block I want to test is:
```Ruby
  describe "associated_updated_at" do
    it "returns the latest updated at timestamp" do
      community = FactoryBot.create(:community, updated_at: 1.day.ago)
      speaker = FactoryBot.create(:speaker, community: community)
      place = FactoryBot.create(:place, community: community)
      story = FactoryBot.create(:story, community: community, speakers: [speaker], places: [place])

      expect(community.associated_updated_at).to eq(story.updated_at)

    end

    it "handles nil" do
      expect { community.associated_updated_at }.not_to raise_error
    end
  end
```

**Comment by rudokemper** [comment]
Hi @ashwini-seshadri looks like tests are not fully operational on Terrasrories at the moment.. I'd skip this and submit the rest of your PR when it's ready :)

**Comment by ashwini-seshadri** [comment]
Hi, @rudokemper 
I have submitted the PR, although, due to some unforeseen git issues on my local computer, I am unable to push the commit for Matawai/Dutch language update. I will do so by morning! 🙏🏾

**Comment by ashwini-seshadri** [comment]
Hi @rudokemper I request a review for this PR.
Thank you!

**Review by rudokemper — APPROVED** [review]
Looks great! Thanks @ashwini-seshadri for this contribution :)

**Pull request merged**
