### PR TITLE
[#313] Setup Rubocop for Ruby

### PR DESCRIPTION
**Pull request by rgenchev**
Closes https://github.com/Terrastories/terrastories/issues/313

### CODE REVIEW

**Comment by midhunkrishna** [comment]
@rgenchev I wasn't sure about the readme either. You can update readme like this in this PR -> https://github.com/Terrastories/terrastories/pull/338/files#diff-550856cf67eb7260aaeb883550043af8R143-R149

**Comment by mirandawang** [comment]
@rgenchev Thanks for the contribution!! Rubocop seems like it could be helpful. Can you describe more about what rules you're adding and what benefits you think they would bring? I'm wary to add too many rules that would block other people!

**Comment by rgenchev** [comment]
> @rgenchev Thanks for the contribution!! Rubocop seems like it could be helpful. Can you describe more about what rules you're adding and what benefits you think they would bring? I'm wary to add too many rules that would block other people!

@mirandawang, sure. :)

I used what was discussed here: https://github.com/Terrastories/terrastories/issues/313#issuecomment-543311629

We use the default `Rubocop` configuration. We'll later work on 2 other PRs.

**Comment by FeminismIsAwesome** [comment]
@rgenchev  hi is this still being worked on? we just did a refactor that will require rebasing (moving the Rails app to a Rails directory)

**Comment by FeminismIsAwesome** [comment]
Closing for now due to rebasing needs, can be reopened with those changes.

**Pull request closed without merging**
