### PR TITLE
Added tranalation to hindi language 

### PR DESCRIPTION
**Pull request by AshishSharma1203**
Regarding issue #826 

Added Hindi (hi) language translation support.
Created hi folder and created hi.yml file .
I will add the remaining file step by step.

### CODE REVIEW

**Comment by rudokemper** [comment]
Hi @AshishSharma1203 , thanks for this! Can you also translate all of the languages to punjabi, and add hindi? This part:

```    am: Amharic
    en: English
    es: Spanish
    ja: Japanese
    mat: Matawai
    nl: Dutch
    pt: Portuguese
    sw: Swahili
    zh: Chinese
    pu: Punjabi

**Comment by AshishSharma1203** [comment]
> Hi @AshishSharma1203 , thanks for this! Can you also translate all of the languages to punjabi, and add hindi? This part:
> 
> ```
>     en: English
>     es: Spanish
>     ja: Japanese
>     mat: Matawai
>     nl: Dutch
>     pt: Portuguese
>     sw: Swahili
>     zh: Chinese
>     pu: Punjabi
> ```

I think you mismatched something. I have added Hindi translation file. So i have to translate the above languages to hindi and add punjabi . is it soo ??

**Comment by rudokemper** [comment]
@AshishSharma1203 ah yeah pardon, was responding to two similar pull requests as you might have seen.

Yes, add Punjabi, and then translate all of the above languages to Hindi.

**Comment by AshishSharma1203** [comment]
> @AshishSharma1203 ah yeah pardon, was responding to two similar pull requests as you might have seen.
> 
> Yes, add Punjabi, and then translate all of the above languages to Hindi.

donneee i have made the changes 
review it and merge it

**Comment by AshishSharma1203** [comment]
> @AshishSharma1203 ah yeah pardon, was responding to two similar pull requests as you might have seen.
> 
> Yes, add Punjabi, and then translate all of the above languages to Hindi.

its fine sir,, and yeah  Punjabi translation was made by my friend.  😄😄

**Review by rudokemper — APPROVED** [review]

**Comment by rudokemper** [comment]
Thanks @AshishSharma1203 :)

**Pull request merged**
