### PR TITLE
Add .gitattributes andrenormalize. 

### PR DESCRIPTION
**Pull request by lauramosher**
We may need to run this again on Windows rather than my mac. I feel like I had a different set of files changed after renormalizing.

This should fix the issue with line endings. 🤞

### CODE REVIEW

**Comment by mirandawang** [comment]
I realized I should review this on a Windows machine, so I'll need to wait til I get that set up 😅  Got my eyes on this though!

**Comment by rudokemper** [comment]
This is to resolve the line ending issues, right? I can try it out on Windows :)

**Comment by mirandawang** [comment]
@rudokemper Yes! Please do :)

**Comment by FeminismIsAwesome** [comment]
@rudokemper what was the result? i cant really accept this works, as i dont have a windows machine

**Comment by rudokemper** [comment]
@FeminismIsAwesome yes, I can confirm this branch worked out per my testing! ✔️

**Review by rudokemper — APPROVED** [review]
LGTM! Tried it on Windows and it works.

**Comment by lauramosher** [comment]
@rudokemper I just rebased with the latest on main and reran renormalize; can you verify this still works for you on windows with a fresh pull? IF so, merge away!

**Pull request merged**
