### PR TITLE
translated to punjabi language

### PR DESCRIPTION
**Pull request by anupeshverma**
Regarding issue #826 

Translated into Punjabi(Indian) language.
Please accept the PR.

### CODE REVIEW

**Comment by AshishSharma1203** [comment]
Is this completed ??

**Comment by rudokemper** [comment]
Hi @anupeshverma, thanks for this. Can you also translate all of the languages to punjabi, and add hindi? This part:

```    am: Amharic
    en: English
    es: Spanish
    ja: Japanese
    mat: Matawai
    nl: Dutch
    pt: Portuguese
    sw: Swahili
    zh: Chinese
    pu: Punjabi

**Comment by anupeshverma** [comment]
Done ✔️

**Review by rudokemper — APPROVED** [review]

**Comment by rudokemper** [comment]
Thanks @anupeshverma! :)

**Pull request merged**
