### PR TITLE
display an better error message when nginx 502s

### PR DESCRIPTION
**Pull request by robbkidd**
502 most likely means the Rails process is not responding (down or still starting up). Display a meaningful message instead of the enigmatic "Bad Gateway" no soup for you message.

Changed the nginx service to be built from an image so that the error page could be added directly to the image. Also added dockerize to handle the template rendering for the nginx config.

Removed NODE_ENV and RAILS_ENV environment variables as unnecessary for the nginx service.

This is an alternative to #208 (the one [mentioned there as Better Error Message](https://github.com/rubyforgood/terrastories/pull/208#issuecomment-471228562)).

Looks like this currently, but obviously the words are negotiable:

Screen Shot 2019-03-11 at 4 36 16 PM

### CODE REVIEW

**Comment by robbkidd** [comment]
Something to consider: as written at the moment, this page will appear as-is for field units when the Rails process causes a 502 in nginx.

**Comment by mirandawang** [comment]
What do you mean by field units?

**Comment by robbkidd** [comment]
The Terrastories instances running standalone "in production" in communities. It's my understanding that those installs use this docker-compose config and these dockerfiles (or at least the images generated by them).

With this change, a Terrastories NUC in a community would display this error page until the Rails web service was up and responsive.

**Comment by Bootjack** [comment]
Hey, I had started something very similar here https://github.com/rubyforgood/terrastories/compare/69-startup-message although it looks like you might have gotten to a more complete point. I did try to add polling to the "sorry" screen so that it would automatically redirect to the login page as soon as it get's a successful response from the rails app. I'd love to hear your thoughts on that.

**Comment by mirandawang** [comment]
https://github.com/Terrastories/terrastories/pull/208

**Comment by mirandawang** [comment]
closing for now; thank you for this work!

**Pull request closed without merging**
