### PR TITLE
Fixes height of card containing StoryList

### LINKED ISSUE #789: [UI] Height of StoryList view exceeds viewport in mobile
**Describe the bug**
The height of the mobile StoryList view exceeds the viewport in mobile. In the screenshot below (Samsung Galaxy A71), you can see that the bottom content of the StoryList `Hello username (Back to Welcome Page) Admin Page` is not shown. 

Screenshot_20220729-084243_Chrome

This especially becomes an issue for phones that automatically scroll down on the page when a dropdown is selected. I've seen this on one device where they selected something for the second filter, and it scrolled down on the StoryList thereby hiding the `X` on the top to return to the map view.

**To Reproduce**
1. On a mobile device, go to https://our.terrastories.io and log in with username `terrastories-developer@terrastories.io` and password `terrastories`.
2. Enter Site
3. Press on the arrow button on the top left to bring the StoryList into view.
4. See the bug

**Expected behavior**
The bottom content of the StoryList `Hello username (Back to Welcome Page) Admin Page` is always shown on the bottom regardless of Viewport size.

### PR DESCRIPTION
**Pull request by asheerrizvi**
Closes #789 

Screenshot:
image

### CODE REVIEW

**Comment by asheerrizvi** [comment]
@rudokemper can you have a look at this as well? 😸

**Comment by lauramosher** [comment]
@asheerrizvi Can you please update your branch with the latest from master? Somehow your branch has a copy of all of the recent commits.

**Comment by asheerrizvi** [comment]
@lauramosher hey, I did merge master into my branch. This was the commit [4447903](https://github.com/Terrastories/terrastories/pull/813/commits/4447903b5167034ccdfc38c545f5d4444183bf10). Not sure why it is showing other commits here.

**Comment by asheerrizvi** [comment]
Says I am up to date with `master` :/

image

**Comment by lauramosher** [comment]
Hmm. A couple of options.

You can try running a rebase instead of a merge — this should drop the ones already merged and will apply your commits at the end.

Or, you can cherry pick your commits and apply them to a freshly created branch from master.

**Comment by asheerrizvi** [comment]
@lauramosher here you go: https://github.com/Terrastories/terrastories/pull/819

**Pull request closed without merging**
