### PR TITLE
Allow some basic HTML tags in story description

### PR DESCRIPTION
**Pull request by julinvictus**
Screen Shot 2023-09-28 at 4 01 03 PM
Screen Shot 2023-09-28 at 4 02 35 PM
Screen Shot 2023-09-28 at 6 11 19 PM
Screen Shot 2023-11-01 at 7 26 19 PM

### CODE REVIEW

**Comment by rudokemper** [comment]
Nice work, @julinvictus!

Can you make this work on the React side as well?

**Review by rudokemper — APPROVED** [review]
Looks good! We'll just need to make sure this also works in the React front end. I think it'd be fine to merge this  as-is and do a follow-up PR, or amend this PR to also get the HTML tag working in React.

**Comment by julinvictus** [comment]
> Looks good! We'll just need to make sure this also works in the React front end. I think it'd be fine to accept this as-is, but to merge we should first do a follow-up PR, or amend this PR to also get the HTML tag working in React.

I can take a look at the react part

**Comment by julinvictus** [comment]
When you say React you mean this part here, right?

**Comment by julinvictus** [comment]
When you say React you mean this part here, right?
Screen Shot 2023-10-16 at 7 47 31 PM

**Comment by rudokemper** [comment]
Correct

**Pull request merged**
